import ProjectDescription

let workspace = Workspace(
  name: "Julook",
  projects: [
    "Projects/App"
  ],
  schemes: [
    .scheme(
      name: "Julook",
      buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: "Julook")]),
      runAction: .runAction(
        configuration: .debug,
        arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
      ),
      archiveAction: .archiveAction(configuration: .release),
      profileAction: .profileAction(configuration: .release),
      analyzeAction: .analyzeAction(configuration: .release)
    )
  ],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)

//    .scheme(
//      name: "Dev-Julook",
//      buildAction: .buildAction(targets: [.project(path: "./Projects/App", target: "Dev-Julook")]),
//      runAction: .runAction(
//        configuration: .debug,
//        arguments: .arguments(environmentVariables: ["IDEPreferLogStreaming": "YES"])
//      ),
//      archiveAction: .archiveAction(configuration: .debug),
//      profileAction: .profileAction(configuration: .debug),
//      analyzeAction: .analyzeAction(configuration: .debug)
//    )
