#!/usr/bin/env bash
# scripts/pre-push.sh
# 푸시 전 차단/경고 체크. 근거: docs/git/push-check.md
# 비상 우회: SKIP_ALL=1 git push          (전부 스킵 — 비상용)
#          SKIP_BUILD_TESTS=1 git push    (빌드/테스트만 스킵)

set -uo pipefail

RED='\033[0;31m'; YEL='\033[0;33m'; GRN='\033[0;32m'; BOLD='\033[1m'; NC='\033[0m'
FAIL=0; WARN=0
fail() { echo -e "${RED}✗ $1${NC}"; FAIL=$((FAIL+1)); }
warn() { echo -e "${YEL}⚠ $1${NC}"; WARN=$((WARN+1)); }
ok()   { echo -e "${GRN}✓ $1${NC}"; }
sec()  { echo -e "\n${BOLD}▶ $1${NC}"; }

if [[ "${SKIP_ALL:-0}" == "1" ]]; then
  echo -e "${YEL}SKIP_ALL=1 — pre-push 체크 전체 스킵${NC}"; exit 0
fi

ROOT="$(git rev-parse --show-toplevel)"; cd "$ROOT"
BRANCH="$(git rev-parse --abbrev-ref HEAD)"

# push 대상 범위 결정
if git rev-parse --verify "@{u}" >/dev/null 2>&1; then
  RANGE="@{u}..HEAD"
else
  for base in origin/develop origin/main develop main; do
    git rev-parse --verify "$base" >/dev/null 2>&1 && { RANGE="$base..HEAD"; break; }
  done
  RANGE="${RANGE:-HEAD~10..HEAD}"
fi
CHANGED="$(git diff --name-only $RANGE 2>/dev/null || true)"
COMMITS="$(git log --format=%s $RANGE 2>/dev/null || true)"

# ── [차단 1] main 직접 푸시 금지 ─────────────────────────
sec "[차단 1] main 직접 푸시 금지"
if [[ "$BRANCH" == "main" ]]; then
  fail "main 브랜치 직접 푸시 금지 — feature/* 에서 PR로 올릴 것."
else
  ok "현재 브랜치: $BRANCH"
fi

# ── [차단 2] Secrets 유출 ────────────────────────────────
sec "[차단 2] Secrets 유출"
SECRET_FILES_RE='(Secrets\.xcconfig|\.env$|\.env\.[^/]+|GoogleService-Info\.plist)'
SECRET_CONTENT_RE='(API_KEY|SECRET|PASSWORD|TOKEN)[[:space:]]*[=:][[:space:]]*["'\'']?[A-Za-z0-9_-]{16,}'

LEAKED="$(echo "$CHANGED" | grep -E "$SECRET_FILES_RE" || true)"
if [[ -n "$LEAKED" ]]; then
  fail "Secrets 파일 변경이 포함됨:"
  echo "$LEAKED" | sed 's/^/    /'
  echo "    → .gitignore 등록, 이미 커밋됐다면 git-filter-repo 로 제거."
fi
LEAKED_LINES="$(git diff $RANGE -- 2>/dev/null | grep -E '^\+' | grep -vE '^\+\+\+' | grep -E "$SECRET_CONTENT_RE" || true)"
if [[ -n "$LEAKED_LINES" ]]; then
  fail "커밋된 변경에 API 키/토큰 리터럴로 보이는 줄 있음."
  echo "$LEAKED_LINES" | head -3 | sed 's/^/    /'
fi
[[ -z "$LEAKED" && -z "$LEAKED_LINES" ]] && ok "Secrets 유출 패턴 없음."

# ── [차단 3] print( 직접 사용 금지 ───────────────────────
sec "[차단 3] print( 직접 사용 금지 (Log 사용)"
SWIFT_SRC="$(echo "$CHANGED" | grep -E '\.swift$' | grep -vE '(Tests/|Preview|scripts/fixtures/)' || true)"
PRINT_HITS=""
while IFS= read -r f; do
  [[ -z "$f" || ! -f "$f" ]] && continue
  h="$(grep -nE '^[[:space:]]*print\(' "$f" || true)"
  [[ -n "$h" ]] && PRINT_HITS+="  $f:\n$h\n"
done <<< "$SWIFT_SRC"
if [[ -n "$PRINT_HITS" ]]; then
  fail "print() 직접 사용 금지. Log.debug / Log.network / Log.error 사용:"
  echo -e "$PRINT_HITS" | head -10 | sed 's/^/  /'
else
  ok "print( 없음."
fi

# ── [차단 4] 라인 제한 (함수 50 / 타입 300 / 파일 400) ────
sec "[차단 4] 라인 제한"
SWIFT_ALL="$(echo "$CHANGED" | grep -E '\.swift$' || true)"
LIMIT_HIT=0
while IFS= read -r f; do
  [[ -z "$f" || ! -f "$f" ]] && continue
  head -5 "$f" | grep -qE '(Generated|DesignSystemAsset|autogenerated)' && continue

  lines=$(wc -l < "$f" | tr -d ' ')
  (( lines > 400 )) && { fail "파일 ${lines}줄 (> 400): $f"; LIMIT_HIT=1; }

  awk -v F="$f" '
    function report(kind, limit, start, end) {
      len = end - start + 1
      if (len > limit) printf "  %s:%d: %s %d줄 (> %d)\n", F, start, kind, len, limit
    }
    {
      for (i=1; i<=length($0); i++) {
        c = substr($0, i, 1)
        if (c == "{") { depth++
          if (pending_kind != "" && pending_start > 0 && !stack_kind[depth]) {
            stack_kind[depth] = pending_kind
            stack_limit[depth] = pending_limit
            stack_start[depth] = pending_start
            pending_kind = ""
          }
        }
        if (c == "}") {
          if (stack_kind[depth] != "") {
            report(stack_kind[depth], stack_limit[depth], stack_start[depth], NR)
            stack_kind[depth] = ""
          }
          depth--
        }
      }
      if (pending_kind == "") {
        if ($0 ~ /func[[:space:]]+[A-Za-z_]/)                { pending_kind="func"; pending_limit=50;  pending_start=NR }
        else if ($0 ~ /(struct|class|enum|actor)[[:space:]]+[A-Z]/) { pending_kind="type"; pending_limit=300; pending_start=NR }
      }
    }
  ' "$f" | while read -r line; do
    warn "$line"
  done
done <<< "$SWIFT_ALL"
(( LIMIT_HIT == 0 )) && ok "파일 400줄 제한 통과 (함수/타입 초과는 경고로 출력됨)."

# ── [차단 5] 프로덕션 변경 시 테스트 동반 ─────────────────
sec "[차단 5] 프로덕션 변경 시 테스트 동반 (TDD)"
PROD="$(echo "$CHANGED" | grep -E 'Projects/[^/]+/Sources/.*\.swift$|supabase/functions/' || true)"
TEST="$(echo "$CHANGED" | grep -E '/Tests/.*\.swift$' || true)"
if [[ -n "$PROD" && -z "$TEST" ]]; then
  fail "프로덕션 코드만 변경됨. Tests/ 변경 없음:"
  echo "$PROD" | head -5 | sed 's/^/    /'
  echo "    → docs/tdd/enforcement.md"
elif [[ -z "$PROD" ]]; then
  ok "프로덕션 코드 변경 없음."
else
  ok "프로덕션 + 테스트 동반."
fi

# ── [차단 7] 커밋 메시지 형식 ─────────────────────────────
sec "[차단 7] 커밋 메시지 형식 ({이모지} [{type}] ...)"
BAD=0
MSG_RE='^(✨|🐛|♻️|📝|🎨|🚀|🙈|💄|🔥|🔒|⚡️|✅|🛠️) \[(feat|fix|refactor|docs|style|deploy|chore|ui|perf|security|test)\] '
while IFS= read -r msg; do
  [[ -z "$msg" ]] && continue
  # 시스템 merge 커밋 (Merge branch / Merge tag / Merge <branch-name> 등)은 형식 검증 제외
  if [[ "$msg" == Merge* ]]; then
    continue
  fi
  if ! echo "$msg" | grep -qE "$MSG_RE"; then
    fail "형식 불일치: $msg"; BAD=$((BAD+1))
  fi
done <<< "$COMMITS"
(( BAD == 0 )) && ok "커밋 메시지 형식 OK."

# ── [차단 8] WIP / 임시 커밋 ─────────────────────────────
sec "[차단 8] WIP/임시 커밋"
WIP="$(echo "$COMMITS" | grep -iE 'wip|fixme|임시|asdf|test[[:space:]]*123' || true)"
if [[ -n "$WIP" ]]; then
  fail "WIP/임시 커밋 감지 (푸시 전 squash 필수):"
  echo "$WIP" | sed 's/^/    /'
else
  ok "WIP/임시 커밋 없음."
fi

# ── [차단 10] SwiftLint ──────────────────────────────────
sec "[차단 10] SwiftLint"
if command -v swiftlint >/dev/null 2>&1 && [[ -f ".swiftlint.yml" ]]; then
  # error 수준 위반만 차단, warning은 출력하되 통과
  LINT_ERRORS="$(swiftlint --quiet 2>&1 | grep 'error:' || true)"
  if [[ -n "$LINT_ERRORS" ]]; then
    fail "SwiftLint error 수준 위반:"
    echo "$LINT_ERRORS" | head -5 | sed 's/^/    /'
  else
    ok "SwiftLint error 없음 (warning은 허용)."
  fi
else
  ok "SwiftLint 미설치 또는 설정 없음 (스킵)."
fi

# ── [차단 6] 빌드 + 테스트 ───────────────────────────────
sec "[차단 6] 빌드 + 전체 테스트"
if [[ "${SKIP_BUILD_TESTS:-0}" == "1" ]]; then
  warn "SKIP_BUILD_TESTS=1 — 빌드/테스트 스킵 (위험)."
else
  echo "    (느림: tuist generate + xcodebuild test)"
  if ! command -v tuist >/dev/null 2>&1 && ! command -v mise >/dev/null 2>&1; then
    fail "tuist / mise 미설치. 빌드 불가."
  else
    TUIST_CMD="tuist"
    command -v mise >/dev/null 2>&1 && TUIST_CMD="mise exec -- tuist"

    if ! TUIST_ROOT_DIR="$ROOT" $TUIST_CMD generate --no-open >/tmp/julook_tuist.log 2>&1; then
      fail "tuist generate 실패. 로그: /tmp/julook_tuist.log"
    elif ! xcodebuild \
            -workspace Julook.xcworkspace \
            -scheme "Julook (App project)" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.5' \
            -quiet \
            test >/tmp/julook_test.log 2>&1; then
      fail "빌드/테스트 실패. 로그 마지막 40줄:"
      tail -40 /tmp/julook_test.log | sed 's/^/    /'
    else
      ok "빌드 성공 + 전체 테스트 통과."
    fi
  fi
fi

echo ""
echo "─────────────────────────────────────"
if (( FAIL > 0 )); then
  echo -e "${RED}${BOLD}✗ 푸시 차단: 차단 ${FAIL}건 / 경고 ${WARN}건${NC}"
  echo "   비상 우회: SKIP_ALL=1 git push  (반드시 사후 조치)"
  exit 1
else
  echo -e "${GRN}${BOLD}✓ 푸시 허용 (경고 ${WARN}건)${NC}"
  exit 0
fi
